02-js-data-types 2-pick
js-tasks-ru/js-20201211_sovtara pull request #2
Opened 2020-12-21 14:26 UTC by sovtara

2020-12-21 14:39 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-12-21 14:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-21 15:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-22 06:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-22 07:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-22 07:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-22 09:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-22 12:08 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const fields = path.split('.');
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2020-12-22 12:08 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
нужно просто `return`

2020-12-22 12:09 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(uniq.values());
через Set можно решить гораздо короче:
```
return [...new Set(arr)];
```

2020-12-22 12:10 UTC, dosandk requested changes
необходимо внести правки в `createGetter` решение

2020-12-22 12:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-12-24 13:37 UTC, dosandk approved these changes
good 👍

2020-12-24 13:38 UTC, merged